version: "3.8"

services:
  consumer:
    container_name: consumer
    image: registry.i2cat.net/edc-0.7.1/connector-0.7.1@sha256:e78cf9ddab0709865150e12c39d8bb444876b71657756b953550dd06c02a7730
    volumes:
      - ./settings:/open-telemetry
      - ./resources:/resources
    ports:
      - "29193:29193"
      - "29194:29194"
      - "25005:5005"
    environment:
      REMOTE_DEBUG: "false" # Enable remote debugging [true/false]
      REMOTE_DEBUG_SUSPEND: "n" # Suspend until debugger is attached [y/n]
      REMOTE_DEBUG_BIND: "*:5005"
      EDC_HOSTNAME: consumer
      OTEL_SERVICE_NAME: consumer
      OTEL_JAVAAGENT_EXTENSIONS: /app/opentelemetry-exporter-otlp.jar
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_METRICS_EXPORTER: prometheus
      WEB_HTTP_PORT: 29191
      WEB_HTTP_PATH: /api
      WEB_HTTP_PUBLIC_PORT: 29291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 29192
      WEB_HTTP_CONTROL_PATH: /control
      WEB_HTTP_MANAGEMENT_PORT: 29193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 29194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_CONTROL_ENDPOINT: http://consumer:29192/control
      EDC_DSP_CALLBACK_ADDRESS: http://consumer:29194/protocol
      EDC_PARTICIPANT_ID: consumer
      EDC_API_AUTH_KEY: password
      EDC_KEYSTORE: /resources/certs/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_VAULT: /resources/configuration/provider-vault.properties
      EDC_FS_CONFIG: /resources/configuration/provider-configuration.properties

  provider:
    container_name: provider
    image: registry.i2cat.net/edc-0.7.1/connector-0.7.1@sha256:e78cf9ddab0709865150e12c39d8bb444876b71657756b953550dd06c02a7730
    volumes:
      - ./settings:/open-telemetry
      - ./resources:/resources
    ports:
      - "19193:19193"
      - "19192:19192"
    environment:
      EDC_HOSTNAME: provider
      OTEL_SERVICE_NAME: provider
      OTEL_LOGS_EXPORTER: none
      OTEL_JAVAAGENT_EXTENSIONS: /app/opentelemetry-exporter-otlp.jar
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_METRICS_EXPORTER: prometheus
      WEB_HTTP_PORT: 19191
      WEB_HTTP_PATH: /api
      WEB_HTTP_PUBLIC_PORT: 19291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 19192
      WEB_HTTP_CONTROL_PATH: /control
      WEB_HTTP_MANAGEMENT_PORT: 19193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 19194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_CONTROL_ENDPOINT: http://provider:19192/control
      EDC_DSP_CALLBACK_ADDRESS: http://provider:19194/protocol
      EDC_PARTICIPANT_ID: provider
      EDC_API_AUTH_KEY: password
      EDC_KEYSTORE: /resources/certs/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_VAULT: /resources/configuration/consumer-vault.properties
      EDC_FS_CONFIG: /resources/configuration/consumer-configuration.properties
      EDC_SAMPLES_TRANSFER_01_ASSET_PATH: /open-telemetry/README.md

  http-server:
    container_name: http-server
    image: registry.i2cat.net/edc-0.7.1/http-server@sha256:80aef89e93de8bfd64eb3c49948097be4e396d29884df239453599f8cd6025b6
    ports:
      - "8080:8080"
