name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: design_decisions/repository_mgmt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run web structure script
        working-directory: design_decisions/repository_mgmt
        run: |
          python create_web_structure.py --base-dir ../../web/docs/tech-testing/results
          
      - name: Run web content script
        working-directory: design_decisions/repository_mgmt
        run: |
          python create_web_content.py -i ../../tests -o ../../web/docs/tech-testing/results --github-base-url ${{ vars.REPO_TESTS_BASE_URL }}

      - name: Run score matrix script
        working-directory: design_decisions/repository_mgmt
        run: |
          python create_result_table.py --base-dir ../../tests/ --output-file ../../web/docs/tech-testing/results/score_matrix.mdx --github-base-url ${{ vars.REPO_BASE_URL }}

      - name: Build And Deploy Docusaurus
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_DESERT_0898CBB03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_DESERT_0898CBB03 }}
          action: "close"
